"""Generated by types-for-jinja from yak/edit.html.jinja. Do not edit by hand."""

from __future__ import annotations

from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_edit(*, yak_name: str, yak_path: str, content: str, category: str, category_color: str, frontmatter: dict[str, object], backlinks: list[tuple[str, str]], current_route: str) -> HTMLResponse:
    """Render yak/edit.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('yak/edit.html.jinja').render(yak_name=yak_name, yak_path=yak_path, content=content, category=category, category_color=category_color, frontmatter=frontmatter, backlinks=backlinks, current_route=current_route))
