"""Generated by types-for-jinja from yak/new.html.jinja. Do not edit by hand."""

from __future__ import annotations

from collections.abc import Callable
from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_new(*, categories: set[str], get_category_color: Callable[[str], str], current_route: str) -> HTMLResponse:
    """Render yak/new.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('yak/new.html.jinja').render(categories=categories, get_category_color=get_category_color, current_route=current_route))
