# Configuration file for golangci-lint
# For more options, see https://golangci-lint.run/usage/configuration/
#
# Adapted from:
# - https://github.com/elastic/elastic-agent/blob/ad06a2989e715220009cd8b27b4a315c92a24b15/.golangci.yml
# - https://github.com/virtual-kubelet/virtual-kubelet/blob/5c534ffcd6074044b00a5151da84ac2cc8ce3f12/.golangci.yml
# - https://github.com/containerd/containerd/blob/b22a302a75d9a7d7955780e54cc5b32de6c8525d/.golangci.yml

[linters] # Find the whole list here https://golangci-lint.run/usage/linters/
default = "standard"
enable = [
  "errcheck", # checking for unchecked errors in go programs
  "errorlint", # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
  "forbidigo", # forbids identifiers	matched by reg exps
  "gosimple", # linter for Go source code that specializes in simplifying a code
  "misspell", # finds commonly misspelled English words in comments
  "nakedret", # finds naked returns in functions greater than a specified function length
  "nolintlint", # reports ill-formed or insufficient nolint directives
  "staticcheck", # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
  "stylecheck", # a replacement for golint
  "unused", # checks Go code for unused constants, variables, functions and types
  "govet", # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
  "ineffassign", # detects when assignments to existing variables are not used
  "typecheck", # Like the front-end of a Go compiler, parses and type-checks Go code
  "asciicheck", # simple linter to check that your code does not contain non-ASCII identifiers
  "bodyclose", # checks whether HTTP response body is closed successfully
  "durationcheck", # check for two durations multiplied together
  "goimports", # Goimports does everything that gofmt does. Additionally it checks unused imports
  "gosec", # inspects source code for security problems
  "importas", # enforces consistent import aliases
  "nilerr", # finds the code that returns nil even if it checks that the error is not nil.
  "noctx", # noctx finds sending http request without context.Context
  "unconvert", # Remove unnecessary type conversions
  "wastedassign", # wastedassign finds wasted assignment statements.
  "depguard", # check for blocked imports from Go files
  "gomodguard", # check for blocked imports from go.mod
  "gomoddirectives", # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
]

[linters.settings] # See all configuration here: https://golangci-lint.run/usage/linters

[linters.settings.rowserrcheck]
packages = ["github.com/jmoiron/sqlx"]

[linters.settings.staticcheck]
checks = ["all"]

[run]
timeout = "1m" # Default is 1 min
