# Configuration file for golangci-lint
# For more options, see https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - deadcode
    - gosimple
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - scopelint
    - prealloc
    - goconst
    - gocritic
    - dupl
    - exportloopref
    - nakedret
    - makezero

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  format: colored-line-number
  sort-results: true
