[settings]
experimental = true # required for go for now

[tasks.ci]
depends = ["test"]
description = "Use in GitHub Actions"

[tasks.format]
description = "Format code"
run = ["hk fix --quiet"]
sources = ['**/*.go']

[tasks.install-system]
description = "Install latest code system-wide"
run = "go install ."

[tasks.test]
description = "Run test"
# https://stackoverflow.com/a/21725603/3219667
run = "go test -coverprofile=coverage.out -coverpkg=./... ./..."
sources = ['**/*.go']

[tasks.test-new]
description = "Create a new note in the global test folder"
run = "SHEARS_SUBDIR=test go run . new -o"

[tasks.test-view-coverage]
description = "View last run test coverage. Alternatively, use `gocovsh`"
# https://go.dev/blog/cover#heat-maps
run = "go tool cover -html=coverage.out"

[tasks.update]
description = "Update dependencies"
run = ["go get -u ./...", "go mod tidy"]

[tools] # Upgrade with `mise upgrade --bump`
go = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/rhysd/actionlint/cmd/actionlint" = "latest"
"pipx:commitizen" = "latest"
"pipx:pre-commit-hooks" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:toml-sort" = "latest"
