[tasks.format]
description = "Format code"
run = ["go fmt ./...", "testifylint --enable-all --fix ./..."]
sources = ['**/*.go']

[tasks.hooks]
description = "Run git hook fixes"
run = ["hk check --quiet", "hk fix --quiet"]

[tasks.install-system]
description = "Install latest code system-wide"
run = "go install ."

[tasks.test]
description = "Run test"
# https://stackoverflow.com/a/21725603/3219667
run = "go test -coverprofile=coverage.out -coverpkg=./... ./..."
sources = ['**/*.go']

[tasks.test-coverage]
description = "View test coverage"
# https://go.dev/blog/cover#heat-maps
run = "go tool cover -html=coverage.out"

[tasks.test-new]
description = "Create a new note in the global test folder"
run = "SHEARS_SUBDIR=test go run . new -o"

[tasks.update]
description = "Update dependencies"
run = ["go get -u ./...", "go mod tidy"]

[tools] # Note: all tools are installed by default in CI
go = "1.24.2"
"go:github.com/Antonboom/testifylint" = "1.6.1"
