[tasks.coverage]
description = "View test coverage"
# https://go.dev/blog/cover#heat-maps
run = "go tool cover -html=coverage.out"

[tasks.format]
description = "Format code"
run = ["go fmt ./..."]
sources = ['**/*.go']

[tasks.new-test]
description = "Create a new note in the global test folder"
run = "go run . new -subfolder=test -visual=TextEdit"

[tasks.install]
description = "Install latest code system-wide"
run = "go install ."

[tasks.lint]
depends = ["format"]
description = "Run linters"
run = "testifylint --enable-all ."
sources = ['**/*_test.go']

[tasks.test]
description = "Run test"
# https://stackoverflow.com/a/21725603/3219667
run = "go test -coverprofile=coverage.out -coverpkg=./... ./..."
sources = ['**/*.go']

[tools]
"go:github.com/Antonboom/testifylint" = "1.5.2"
