[env]
_.python.venv = {path = ".venv"}

[tasks.format]
run = ['uv run ruff check --fix {{option(name="unsafe_fixes")}}', "uv run ruff format"]

[tasks.typecheck]
run = ["uv run mypy"]

[tools]
python = ["3.13.3"]
