["tool.sqlfluff.core"]
# PLANNED: This wasn't being recognized?
# dialect = "sqlite"
# PLANNED: revisit templating for Go (https://docs.sqlfluff.com/en/stable/configuration/templating/python.html)
# templater = "python"

["sqlfluff:indentation"]
# PLANNED: revisit
allow_implicit_indents = true

["sqlfluff:rules:capitalisation.keywords"]
capitalisation_policy = "upper"
["sqlfluff:rules:capitalisation.identifiers"]
extended_capitalisation_policy = "upper"
["sqlfluff:rules:capitalisation.functions"]
extended_capitalisation_policy = "upper"
["sqlfluff:rules:capitalisation.literals"]
capitalisation_policy = "upper"
["sqlfluff:rules:capitalisation.types"]
extended_capitalisation_policy = "upper"

["sqlfluff:rules:convention.not_equal"]
# Default to preferring the "c_style" (i.e. `!=`)
preferred_not_equal_style = "c_style"
