"""Generated by types-for-jinja from search/search.html.jinja. Do not edit by hand."""

from __future__ import annotations

from yak_shears._templates import SearchResult
from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_search(*, results: list[SearchResult], query: str, current_route: str) -> HTMLResponse:
    """Render search/search.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('search/search.html.jinja').render(results=results, query=query, current_route=current_route))
