"""Generated by types-for-jinja from auth/login.html.jinja. Do not edit by hand."""

from __future__ import annotations

from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_login(*, redirect: str | None = None, error: str = '') -> HTMLResponse:
    """Render auth/login.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('auth/login.html.jinja').render(redirect=redirect, error=error))
