"""Generated by types-for-jinja from error.html.jinja. Do not edit by hand."""

from __future__ import annotations

from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_error(*, message: str) -> HTMLResponse:
    """Render error.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('error.html.jinja').render(message=message))
