"""Generated by types-for-jinja from yaks/index.html.jinja. Do not edit by hand."""

from __future__ import annotations

from yak_shears._templates import YakInfo, SortBy
from collections.abc import Callable
from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_index(*, yaks: list[YakInfo], current_page: int, total_pages: int, total_yaks: int, yak_dir_label: str, sort_by: SortBy, current_category: str | None, categories: set[str], get_category_color: Callable[[str], str], current_route: str) -> HTMLResponse:
    """Render yaks/index.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('yaks/index.html.jinja').render(yaks=yaks, current_page=current_page, total_pages=total_pages, total_yaks=total_yaks, yak_dir_label=yak_dir_label, sort_by=sort_by, current_category=current_category, categories=categories, get_category_color=get_category_color, current_route=current_route))
