"""Generated by types-for-jinja from settings/index.html.jinja. Do not edit by hand."""

from __future__ import annotations

from collections.abc import Mapping
from yak_shears._yak.categories import ColorSlot
from starlette.responses import HTMLResponse
from yak_shears._templates import ENV as _env
from beartype import beartype


@beartype
def render_index(*, assignments: list[tuple[str, str]], palette: tuple[ColorSlot, ...], owners: Mapping[str, list[str]], saved: bool, current_route: str) -> HTMLResponse:
    """Render settings/index.html.jinja with a checked context."""
    return HTMLResponse(_env.get_template('settings/index.html.jinja').render(assignments=assignments, palette=palette, owners=owners, saved=saved, current_route=current_route))
