# Symlink to `./yak-notes-cli/mise.toml`

[env]
MISE_ENV = 'subproject'

[tasks.format]
description = "Format code"
run = ["golangci-lint run --fix ./...", "golines ./..."]

[tasks.test]
description = "Run test"
# https://stackoverflow.com/a/21725603/3219667
run = "go test -coverprofile=coverage.out -coverpkg=./... ./..."

[tasks."test:view-coverage"]
description = "View last run test coverage. Alternatively, use `gocovsh`"
# https://go.dev/blog/cover#heat-maps
run = "go tool cover -html=coverage.out"

[tasks.update]
description = "Update dependencies"
run = ["go get -u ./...", "go mod tidy"]
