[settings]
experimental = true # required for go for now

[tasks.ci]
depends = ["ci:notes-cli"]
description = "Used in GitHub Actions"

[tasks."ci:notes-cli"]
dir = "../yak-notes-cli/yak-shears"
run = "mise run test"

[tasks.hooks]
description = "Run git hooks"
dir = "./../" # FYI: required because the default is otherwise `.config/` where these files are located
run = ["hk fix --quiet"]

[tools]
go = "latest"
