[env]
MISE_ENV = 'hk'

[settings]
experimental = true # required for go for now

[tasks.ci]
depends = ["ci:geese-migrations", "ci:notes-cli", "ci:web"]
description = "Used in GitHub Actions"

[tasks."ci:geese-migrations"]
dir = "../geese-migrations"
hide = true
run = "mise run test"

[tasks."ci:notes-cli"]
dir = "../yak-notes-cli"
hide = true
run = "mise run test"

[tasks."ci:web"]
dir = "../yak-shears-web"
hide = true
run = "mise run test"

[tasks.hooks]
description = "Run git hooks"
dir = "./../" # FYI: required because the default is otherwise `.config/` where these files are located
run = ["hk fix --quiet"]

[tools]
go = "latest"
