[tools]
"go:github.com/Zxilly/go-size-analyzer/cmd/gsa" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/rhysd/actionlint/cmd/actionlint" = "latest"
"go:github.com/segmentio/golines" = "latest"
ls-lint = "latest"
"pipx:commitizen" = "latest"
"pipx:pre-commit-hooks" = "latest"
"pipx:sqlfluff" = "latest"
"pipx:toml-sort" = "latest"
