---
name: CI

"on":
  push:
    branches: [main]
  workflow_dispatch: null # For manual runs

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true # required for go backend
          install: false # [default: true] runs `mise install`

      - name: Run unit tests
        run: mise run test
